---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "keycloak-deployment"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "keycloak"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "vollmed-apphost"
        app.kubernetes.io/component: "keycloak"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "quay.io/keycloak/keycloak:26.4"
          name: "keycloak"
          envFrom:
            - configMapRef:
                name: "keycloak-config"
          args:
            - "start-dev"
            - "--import-realm"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8080
            - name: "management"
              protocol: "TCP"
              containerPort: 9000
          volumeMounts:
            - name: "keycloak-pgdata"
              mountPath: "/opt/keycloak/data"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "keycloak-pgdata"
          emptyDir: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: "vollmed-apphost"
      app.kubernetes.io/component: "keycloak"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
