---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "vollmed-pacientes-deployment"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-pacientes"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "vollmed-apphost"
        app.kubernetes.io/component: "vollmed-pacientes"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.vollmed_pacientes.vollmed_pacientes_image }}"
          name: "vollmed-pacientes"
          envFrom:
            - configMapRef:
                name: "vollmed-pacientes-config"
            - secretRef:
                name: "vollmed-pacientes-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.vollmed_pacientes.port_http }}
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "vollmed-apphost"
      app.kubernetes.io/component: "vollmed-pacientes"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
