---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "postgres"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  POSTGRES_HOST_AUTH_METHOD: "{{ .Values.config.postgres.POSTGRES_HOST_AUTH_METHOD }}"
  POSTGRES_INITDB_ARGS: "{{ .Values.config.postgres.POSTGRES_INITDB_ARGS }}"
  POSTGRES_USER: "{{ .Values.config.postgres.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.config.postgres.pgPassword }}"
  POSTGRES_DB: "{{ .Values.config.postgres.POSTGRES_DB }}"
