---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "vollmed-consultas-config"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-consultas"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: "{{ .Values.config.vollmed_consultas.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.vollmed_consultas.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.vollmed_consultas.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.vollmed_consultas.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.vollmed_consultas.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.vollmed_consultas.HTTP_PORTS }}"
  CONSULTASDB_HOST: "{{ .Values.config.vollmed_consultas.CONSULTASDB_HOST }}"
  CONSULTASDB_PORT: "{{ .Values.config.vollmed_consultas.CONSULTASDB_PORT }}"
  CONSULTASDB_USERNAME: "{{ .Values.config.vollmed_consultas.CONSULTASDB_USERNAME }}"
  CONSULTASDB_URI: "{{ .Values.config.vollmed_consultas.CONSULTASDB_URI }}"
  CONSULTASDB_JDBCCONNECTIONSTRING: "{{ .Values.config.vollmed_consultas.CONSULTASDB_JDBCCONNECTIONSTRING }}"
  CONSULTASDB_DATABASE: "{{ .Values.config.vollmed_consultas.CONSULTASDB_DATABASE }}"
  RABBITMQ_HOST: "{{ .Values.config.vollmed_consultas.RABBITMQ_HOST }}"
  RABBITMQ_PORT: "{{ .Values.config.vollmed_consultas.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ .Values.config.vollmed_consultas.RABBITMQ_USERNAME }}"
  Api__Uri: "{{ .Values.config.vollmed_consultas.Api__Uri }}"
