---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "vollmed-consultas-service"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-consultas"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-consultas"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "{{ .Values.parameters.vollmed_consultas.port_http }}"
      targetPort: "{{ .Values.parameters.vollmed_consultas.port_http }}"
    - name: "https"
      protocol: "TCP"
      port: "{{ .Values.parameters.vollmed_consultas.port_https }}"
      targetPort: "{{ .Values.parameters.vollmed_consultas.port_https }}"
