parameters:
  vollmed_consultas:
    port_http: "8080"
    port_https: "8080"
    vollmed_consultas_image: "vollmed-consultas:latest"
  vollmed_medicos:
    port_http: "8080"
    port_https: "8080"
    vollmed_medicos_image: "vollmed-medicos:latest"
  vollmed_pacientes:
    port_http: "8080"
    port_https: "8080"
    vollmed_pacientes_image: "vollmed-pacientes:latest"
  vollmed_gateway:
    port_http: "8080"
    port_https: "8080"
    vollmed_gateway_image: "vollmed-gateway:latest"
secrets:
  sqlserver:
    MSSQL_SA_PASSWORD: "Password123!"
  rabbitmq:
    RABBITMQ_DEFAULT_PASS: "guest"
  vollmed_consultas:
    sqlserver_password: "Password123!"
    rabbitmq_password: "guest"
  vollmed_pacientes:
    sqlserver_password: "Password123!"
    rabbitmq_password: "guest"
  vollmed_medicos:
    sqlserver_password: "Password123!"
config:
  postgres:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_PASSWORD: ""
    POSTGRES_DB: "keycloak"
  keycloak:
    KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
    KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    KC_HEALTH_ENABLED: "true"
    KC_DB: "postgres"
    KC_DB_URL: "jdbc:postgresql://postgres-service:5432/keycloakDB"
    KC_DB_USERNAME: "keycloak"
    KC_DB_PASSWORD: "password"
    KEYCLOAK_ADMIN: "admin"
    KEYCLOAK_ADMIN_PASSWORD: "admin"
  sqlserver:
    ACCEPT_EULA: "Y"
  rabbitmq:
    RABBITMQ_DEFAULT_USER: "guest"
  vollmed_consultas:
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    Api__Url: "http://vollmed-gateway-service:8080/"
    CONSULTASDB_HOST: "sqlserver-service"
    CONSULTASDB_PORT: "1433"
    CONSULTASDB_USERNAME: "sa"
    CONSULTASDB_URI: "mssql://sqlserver-service:1433/consultasDB"
    CONSULTASDB_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sqlserver-service:1433;trustServerCertificate=true;databaseName=consultasDB"
    CONSULTASDB_DATABASE: "consultasDB"
    RABBITMQ_HOST: "rabbitmq-service"
    RABBITMQ_PORT: "5672"
    RABBITMQ_USERNAME: "guest"
  vollmed_medicos:
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    MEDICOSDB_HOST: "sqlserver-service"
    MEDICOSDB_PORT: "1433"
    MEDICOSDB_USERNAME: "sa"
    MEDICOSDB_URI: "mssql://sqlserver-service:1433/medicosDB"
    MEDICOSDB_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sqlserver-service:1433;trustServerCertificate=true;databaseName=medicosDB"
    MEDICOSDB_DATABASE: "medicosDB"
  vollmed_pacientes:
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    PACIENTESDB_HOST: "sqlserver-service"
    PACIENTESDB_PORT: "1433"
    PACIENTESDB_USERNAME: "sa"
    PACIENTESDB_URI: "mssql://sqlserver-service:1433/pacientesDB"
    PACIENTESDB_JDBCCONNECTIONSTRING: "jdbc:sqlserver://sqlserver-service:1433;trustServerCertificate=true;databaseName=pacientesDB"
    PACIENTESDB_DATABASE: "pacientesDB"
    RABBITMQ_HOST: "rabbitmq-service"
    RABBITMQ_PORT: "5672"
    RABBITMQ_USERNAME: "guest"
  vollmed_gateway:
    ASPNETCORE_URLS: "http://+:8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    Authentication__KeyCloak__Authority: "http://keycloak-service:8080/realms/VollMed"
    KEYCLOAK_HTTP: "http://keycloak-service:8080"
    services__keycloak__http__0: "http://keycloak-service:8080"
    KEYCLOAK_MANAGEMENT: "http://keycloak-service:9000"
    services__keycloak__management__0: "http://keycloak-service:9000"
