---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "vollmed-medicos-config"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-medicos"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: "{{ .Values.config.vollmed_medicos.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.vollmed_medicos.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.vollmed_medicos.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.vollmed_medicos.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.vollmed_medicos.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.vollmed_medicos.HTTP_PORTS }}"
  MEDICOSDB_HOST: "{{ .Values.config.vollmed_medicos.MEDICOSDB_HOST }}"
  MEDICOSDB_PORT: "{{ .Values.config.vollmed_medicos.MEDICOSDB_PORT }}"
  MEDICOSDB_USERNAME: "{{ .Values.config.vollmed_medicos.MEDICOSDB_USERNAME }}"
  MEDICOSDB_URI: "{{ .Values.config.vollmed_medicos.MEDICOSDB_URI }}"
  MEDICOSDB_JDBCCONNECTIONSTRING: "{{ .Values.config.vollmed_medicos.MEDICOSDB_JDBCCONNECTIONSTRING }}"
  MEDICOSDB_DATABASE: "{{ .Values.config.vollmed_medicos.MEDICOSDB_DATABASE }}"
