---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "vollmed-gateway-config"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "vollmed-gateway"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: "{{ .Values.config.vollmed_gateway.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.vollmed_gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.vollmed_gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.vollmed_gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.vollmed_gateway.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.vollmed_gateway.HTTP_PORTS }}"
  Authentication__KeyCloak__Authority: "{{ .Values.config.vollmed_gateway.Authentication__KeyCloak__Authority }}"
  VOLLMED-CONSULTAS_HTTP: "{{ .Values.config.vollmed_gateway.VOLLMED_CONSULTAS_HTTP }}"
  services__vollmed-consultas__http__0: "{{ .Values.config.vollmed_gateway.services__vollmed_consultas__http__0 }}"
  VOLLMED-CONSULTAS_HTTPS: "{{ .Values.config.vollmed_gateway.VOLLMED_CONSULTAS_HTTPS }}"
  services__vollmed-consultas__https__0: "{{ .Values.config.vollmed_gateway.services__vollmed_consultas__https__0 }}"
  VOLLMED-PACIENTES_HTTP: "{{ .Values.config.vollmed_gateway.VOLLMED_PACIENTES_HTTP }}"
  services__vollmed-pacientes__http__0: "{{ .Values.config.vollmed_gateway.services__vollmed_pacientes__http__0 }}"
  VOLLMED-PACIENTES_HTTPS: "{{ .Values.config.vollmed_gateway.VOLLMED_PACIENTES_HTTPS }}"
  services__vollmed-pacientes__https__0: "{{ .Values.config.vollmed_gateway.services__vollmed_pacientes__https__0 }}"
  VOLLMED-MEDICOS_HTTP: "{{ .Values.config.vollmed_gateway.VOLLMED_MEDICOS_HTTP }}"
  services__vollmed-medicos__http__0: "{{ .Values.config.vollmed_gateway.services__vollmed_medicos__http__0 }}"
  VOLLMED-MEDICOS_HTTPS: "{{ .Values.config.vollmed_gateway.VOLLMED_MEDICOS_HTTPS }}"
  services__vollmed-medicos__https__0: "{{ .Values.config.vollmed_gateway.services__vollmed_medicos__https__0 }}"
  KEYCLOAK_HTTP: "{{ .Values.config.vollmed_gateway.KEYCLOAK_HTTP }}"
  services__keycloak__http__0: "{{ .Values.config.vollmed_gateway.services__keycloak__http__0 }}"
  KEYCLOAK_MANAGEMENT: "{{ .Values.config.vollmed_gateway.KEYCLOAK_MANAGEMENT }}"
  services__keycloak__management__0: "{{ .Values.config.vollmed_gateway.services__keycloak__management__0 }}"
