---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "sqlserver-config"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "sqlserver"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ACCEPT_EULA: "{{ .Values.config.sqlserver.ACCEPT_EULA }}"
