---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "rabbitmq-service"
  labels:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "rabbitmq"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "vollmed-apphost"
    app.kubernetes.io/component: "rabbitmq"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
    - name: "management"
      protocol: "TCP"
      port: 15672
      targetPort: 15672
